import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useResume } from '../context/ResumeContext'
import { aiApi, exportApi } from '../services/api'
import toast from 'react-hot-toast'
import { Wand2, Download, Copy, Sparkles, FileText } from 'lucide-react'

const resumeTypes = [
  { id: 'fresher', label: '🎓 Fresher', desc: 'Recent graduate, skills & projects focused' },
  { id: 'developer', label: '💻 Developer', desc: 'Technical focus, projects & code skills' },
  { id: 'internship', label: '🧑‍🎓 Internship', desc: 'Academic & project-focused' },
  { id: 'experienced', label: '🏢 Experienced', desc: 'Impact-driven, career progression' },
]

const tones = [
  { id: 'professional', label: 'Professional', desc: 'Formal and polished' },
  { id: 'simple', label: 'Simple', desc: 'Clear and direct' },
  { id: 'impact', label: 'Impact Focused', desc: 'Quantified results' },
]

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export default function GeneratorPage() {
  const { sections, resumeType, setResumeType, tone, setTone, generatedText, setGeneratedText, isGenerating, setIsGenerating } = useResume()
  const [jobRole, setJobRole] = useState('')
  const [strengthScore, setStrengthScore] = useState(0)
  const [exporting, setExporting] = useState('')

  const handleGenerate = async () => {
    if (!sections.personal?.name) {
      toast.error('Add your name in Resume Builder first!')
      return
    }
    setIsGenerating(true)
    try {
      const res = await aiApi.generate({
        resumeData: sections,
        resumeType,
        tone,
        jobRole,
      })
      setGeneratedText(res.data.generatedText)
      setStrengthScore(res.data.strengthScore || 0)
      toast.success('Resume generated by Gemini AI! 🎉')
    } catch (e) {
      toast.error(e.response?.data?.error || 'AI generation failed — check your GEMINI_API_KEY')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleExport = async (format) => {
    if (!generatedText) return toast.error('Generate your resume first!')
    setExporting(format)
    try {
      if (format === 'pdf') {
        const res = await exportApi.pdf({ resumeData: sections, generatedText })
        downloadBlob(new Blob([res.data], { type: 'application/pdf' }), 'resume.pdf')
      } else if (format === 'docx') {
        const res = await exportApi.docx({ resumeData: sections, generatedText })
        downloadBlob(new Blob([res.data], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }), 'resume.docx')
      } else {
        const res = await exportApi.txt({ resumeData: sections, generatedText })
        const blob = new Blob([res.data], { type: 'text/plain' })
        downloadBlob(blob, 'resume.txt')
      }
      toast.success(`${format.toUpperCase()} downloaded!`)
    } catch (e) {
      toast.error(`Export failed: ${e.message}`)
    } finally {
      setExporting('')
    }
  }

  const copyToClipboard = async () => {
    if (!generatedText) return toast.error('Generate first!')
    await navigator.clipboard.writeText(generatedText)
    toast.success('Copied to clipboard!')
  }

  return (
    <div className="max-w-6xl mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Controls */}
        <div className="space-y-5">
          <div className="p-6 rounded-2xl border" style={{ background: 'hsl(var(--card))', borderColor: 'hsl(var(--border))' }}>
            <h3 className="text-sm font-semibold mb-4 flex items-center gap-2" style={{ color: 'hsl(var(--foreground))' }}>
              <Wand2 size={15} style={{ color: 'hsl(var(--primary))' }} /> Resume Type
            </h3>
            <div className="grid grid-cols-2 gap-2">
              {resumeTypes.map(rt => (
                <button key={rt.id} onClick={() => setResumeType(rt.id)}
                  className="p-3 rounded-xl border text-left text-xs transition-all"
                  style={{
                    background: resumeType === rt.id ? 'hsl(var(--primary) / 0.15)' : 'hsl(var(--muted))',
                    borderColor: resumeType === rt.id ? 'hsl(var(--primary))' : 'hsl(var(--border))',
                    color: resumeType === rt.id ? 'hsl(var(--primary))' : 'hsl(var(--muted-foreground))',
                  }}>
                  <div className="font-medium">{rt.label}</div>
                  <div className="opacity-70 mt-0.5" style={{ fontSize: '11px' }}>{rt.desc}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="p-6 rounded-2xl border" style={{ background: 'hsl(var(--card))', borderColor: 'hsl(var(--border))' }}>
            <h3 className="text-sm font-semibold mb-4" style={{ color: 'hsl(var(--foreground))' }}>Tone</h3>
            <div className="flex gap-2">
              {tones.map(t => (
                <button key={t.id} onClick={() => setTone(t.id)}
                  className="flex-1 p-2.5 rounded-lg border text-xs transition-all"
                  style={{
                    background: tone === t.id ? 'hsl(var(--primary) / 0.15)' : 'hsl(var(--muted))',
                    borderColor: tone === t.id ? 'hsl(var(--primary))' : 'hsl(var(--border))',
                    color: tone === t.id ? 'hsl(var(--primary))' : 'hsl(var(--muted-foreground))',
                  }}>
                  <div className="font-medium">{t.label}</div>
                  <div style={{ fontSize: '10px', marginTop: '2px' }}>{t.desc}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="p-6 rounded-2xl border" style={{ background: 'hsl(var(--card))', borderColor: 'hsl(var(--border))' }}>
            <label className="block">
              <span className="text-xs font-medium mb-1.5 block" style={{ color: 'hsl(var(--muted-foreground))' }}>
                Target Job Role (optional)
              </span>
              <input value={jobRole} onChange={e => setJobRole(e.target.value)}
                placeholder="e.g. Full Stack Developer at Google"
                className="w-full px-3 py-2.5 rounded-lg text-sm border outline-none"
                style={{ background: 'hsl(var(--input))', borderColor: 'hsl(var(--border))', color: 'hsl(var(--foreground))' }} />
            </label>
          </div>

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full py-3.5 rounded-xl font-semibold text-white flex items-center justify-center gap-2"
            style={{ background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)', opacity: isGenerating ? 0.7 : 1 }}
          >
            {isGenerating ? (
              <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> Generating with Gemini AI...</>
            ) : (
              <><Sparkles size={16} /> Generate Resume with Gemini AI</>
            )}
          </motion.button>

          {strengthScore > 0 && (
            <div className="p-4 rounded-xl border" style={{ background: 'hsl(var(--card))', borderColor: 'hsl(var(--border))' }}>
              <div className="flex justify-between text-xs mb-2">
                <span style={{ color: 'hsl(var(--muted-foreground))' }}>ATS Strength Score</span>
                <span className="font-bold" style={{ color: strengthScore >= 70 ? '#10b981' : strengthScore >= 40 ? '#f59e0b' : '#ef4444' }}>
                  {strengthScore}/100
                </span>
              </div>
              <div className="h-2 rounded-full" style={{ background: 'hsl(var(--muted))' }}>
                <motion.div initial={{ width: 0 }} animate={{ width: `${strengthScore}%` }} transition={{ duration: 1 }}
                  className="h-full rounded-full"
                  style={{ background: strengthScore >= 70 ? '#10b981' : strengthScore >= 40 ? '#f59e0b' : '#ef4444' }} />
              </div>
            </div>
          )}

          {/* Export buttons */}
          <div className="grid grid-cols-3 gap-2">
            {['pdf', 'docx', 'txt'].map(fmt => (
              <button key={fmt} onClick={() => handleExport(fmt)} disabled={!!exporting}
                className="py-2.5 rounded-xl border text-xs font-semibold flex items-center justify-center gap-1.5 transition-all"
                style={{
                  background: 'hsl(var(--muted))',
                  borderColor: 'hsl(var(--border))',
                  color: 'hsl(var(--foreground))',
                  opacity: exporting ? 0.6 : 1,
                }}>
                {exporting === fmt ? <div className="w-3 h-3 border border-current border-t-transparent rounded-full animate-spin" /> : <Download size={12} />}
                {fmt.toUpperCase()}
              </button>
            ))}
          </div>
        </div>

        {/* Right: Preview */}
        <div className="p-6 rounded-2xl border relative" style={{ background: 'hsl(var(--card))', borderColor: 'hsl(var(--border))' }}>
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold flex items-center gap-2" style={{ color: 'hsl(var(--foreground))' }}>
              <FileText size={15} style={{ color: 'hsl(var(--primary))' }} /> Resume Preview
            </h3>
            {generatedText && (
              <button onClick={copyToClipboard}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium"
                style={{ background: 'hsl(var(--muted))', color: 'hsl(var(--muted-foreground))' }}>
                <Copy size={12} /> Copy
              </button>
            )}
          </div>

          <AnimatePresence mode="wait">
            {generatedText ? (
              <motion.pre key="text" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="text-xs leading-relaxed whitespace-pre-wrap overflow-y-auto font-mono"
                style={{
                  color: 'hsl(var(--foreground))',
                  maxHeight: '70vh',
                  fontFamily: '"Courier New", monospace',
                  lineHeight: '1.7',
                }}>
                {generatedText}
              </motion.pre>
            ) : (
              <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="flex flex-col items-center justify-center h-64 text-center">
                <Sparkles size={40} style={{ color: 'hsl(var(--muted-foreground))', opacity: 0.3 }} />
                <p className="mt-4 text-sm" style={{ color: 'hsl(var(--muted-foreground))' }}>
                  Fill in your details and click Generate to see your AI-crafted resume
                </p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  )
}
